# Book settings
title: Machine Learning Lecture
author: Prof. Dr. Johannes Maucher
logo: hdmlogomed.jpg

only_build_toc_files: true

bibtex_bibfiles:
  - maucherML.bib
  
execute:
  execute_notebooks: 'off'

parse:
  myst_url_schemes: [mailto, http, https]
  myst_extended_syntax:
      - dollarmath
      - amsmath
      - linkify
      - fieldlist
      - replacements
      - smartquotes
      - tasklist
      - strikethrough
      - substitution
      - colon_fence
      - html_admonition
      - html_image
      - deflist

latex:
  latex_documents:
    targetname: ml.tex

html:
  only_build_toc_files: true


